variables:
    BUILD_NAME: $CI_PROJECT_NAME-$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID

stages:
    - build

build:
    stage: build
    image: registry.mkz.me/mycroft/build-image-golang
    before_script:
        - apt update
        - apt install -y devscripts build-essential lintian
    script:
        - go get -d -v
        - go build -o tree/usr/bin/$CI_PROJECT_NAME
        - mkdir -p tree/usr/share/$CI_PROJECT_NAME
        - cp config.ini.sample tree/usr/share/$CI_PROJECT_NAME/config.ini.sample
        - debuild -uc -us -i -b
        - mv ../*deb .
    artifacts:
        name: $BUILD_NAME
        paths:
            - ./*deb
